require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
    - db/schema.rb
  TargetRubyVersion: 3.0

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

RSpec/FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
