AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 3.0

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
